#lankerd.groundwork.dashboard:
#    path:     /
#    methods: [GET]
#    defaults:
#        _controller: LankerdGroundworkBundle:Dashboard:index

login:
    path:  /login
    defaults: { _controller: FOSUserBundle:Security:login }

login_check:
    path:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }

logout:
    path:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout }