services:
    core.subscriber:
        class: Lankerd\GroundworkBundle\EventListener\CoreSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    usort.twig.custom_extension:
        class: Lankerd\GroundworkBundle\Twig\CustomSort
        tags:
            - { name: twig.extension }

    is_instance_of.twig.custom_extension:
        class: Lankerd\GroundworkBundle\Twig\IsInstanceOf
        tags:
            - { name: twig.extension }

    groundwork_mailer:
        class: Lankerd\GroundworkBundle\Services\Mailer
        arguments: ["@mailer"]