services:
#    core.subscriber:
#        class: Lankerd\GroundworkBundle\EventListener\CoreSubscriber
#        tags:
#            - { name: doctrine.event_subscriber, connection: default }

    lankerd_groundwork.twig.custom_extension:
        class: Lankerd\GroundworkBundle\Twig\GroundworkTwig
        tags:
            - { name: twig.extension }

    lankerd_groundwork.mailer:
        class: Lankerd\GroundworkBundle\Services\Mailer
        arguments: ["@mailer"]

    lankerd_groundwork.object_handler:
        class: Lankerd\GroundworkBundle\Util\ObjectHandler