services:
    lankerd_groundwork.twig.custom_extension:
        class: Lankerd\GroundworkBundle\Twig\GroundworkTwig
        tags:
            - { name: twig.extension }

    lankerd_groundwork.mailer:
        class: Lankerd\GroundworkBundle\Services\Mailer
        arguments: ["@mailer"]

    Lankerd\GroundworkBundle\Helper\DataHelper: ~

    Lankerd\GroundworkBundle\Helper\QueryHelper:
        arguments: ['@doctrine.orm.entity_manager']

    Lankerd\GroundworkBundle\Handler\DataHandler:
        arguments: ['@Lankerd\GroundworkBundle\Helper\DataHelper', '@form.factory', '@serializer', '@Lankerd\GroundworkBundle\Helper\QueryHelper']
