services:
    lankerd_groundwork.twig.custom_extension:
        class: Lankerd\GroundworkBundle\Twig\GroundworkTwig
        tags:
            - { name: twig.extension }

    lankerd_groundwork.mailer:
        class: Lankerd\GroundworkBundle\Services\Mailer
        arguments: ["@mailer"]

    Lankerd\GroundworkBundle\Handler\ObjectHandler: ~

    Lankerd\GroundworkBundle\Handler\DataHandler:
        arguments: ['@Lankerd\GroundworkBundle\Handler\ObjectHandler', '@doctrine.orm.default_entity_manager', '@form.factory', '@serializer']
