parameters:
    isArchive: true

services:
    lankerd_groundwork.twig.custom_extension:
        class: Lankerd\GroundworkBundle\Twig\GroundworkTwig
        tags:
            - { name: twig.extension }

    lankerd_groundwork.mailer:
        class: Lankerd\GroundworkBundle\Services\Mailer
        arguments: ["@mailer"]

    lankerd_groundwork.helper.data_helper:
        class: Lankerd\GroundworkBundle\Helper\DataHelper

    Lankerd\GroundworkBundle\Helper\DataHelperInterface: '@lankerd_groundwork.helper.data_helper'

    Lankerd\GroundworkBundle\Helper\QueryHelper:
        arguments: ['@doctrine.orm.entity_manager']

    Lankerd\GroundworkBundle\Handler\DataHandler:
        arguments: ['@lankerd_groundwork.helper.data_helper', '@form.factory', '@serializer', '@Lankerd\GroundworkBundle\Helper\QueryHelper','@session','@Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface']

    lankerd_groundwork.serializer.circular_reference_handler:
        class: Lankerd\GroundworkBundle\Serializer\CircularReferenceHandler