services:
#    core.subscriber:
#        class: Lankerd\GroundworkBundle\EventListener\CoreSubscriber
#        tags:
#            - { name: doctrine.event_subscriber, connection: default }

    lankerd.groundwork.twig.custom_extension:
        class: Lankerd\GroundworkBundle\Twig\GroundworkTwig
        tags:
            - { name: twig.extension }

    groundwork_mailer:
        class: Lankerd\GroundworkBundle\Services\Mailer
        arguments: ["@mailer"]