services:
#    core.subscriber:
#        class: Lankerd\GroundworkBundle\EventListener\CoreSubscriber
#        tags:
#            - { name: doctrine.event_subscriber, connection: default }

    usort.twig.custom_extension:
        class: Lankerd\GroundworkBundle\Twig\GroundworkTwig
        tags:
            - { name: twig.extension }

    groundwork_mailer:
        class: Lankerd\GroundworkBundle\Services\Mailer
        arguments: ["@mailer"]

#    lankerd_groundwork.model.core_function_model:
#        class: Lankerd\GroundworkBundle\Model\CoreFunctionModel
##        arguments: ['@doctrine.orm.entity_manager', 'UserBundle\Entity\BillingAddress', '@security.authorization_checker', '@session.flash_bag', '@doctrine.orm.entity_manager']
#        public: true